# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for Trusty TEE
#

obj-$(CONFIG_TRUSTY)		+= trusty.o
trusty-y			:= trusty-core.o trusty-mem.o

obj-$(CONFIG_TRUSTY)		+= trusty-ipc.o
obj-$(CONFIG_TRUSTY)		+= trusty-virtio.o
