// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (c) Google LLC
 *
 * "Boot handoff" panel driver for the Pixel 9 Pro XL (komodo) MIPI-DSI
 * display.
 *
 * The bootloader fully initialises this panel - DCPHY PLL, DSIM link and the
 * panel's own power-on command sequence - and leaves it streaming (that is
 * what the simple-framebuffer splash is drawn into). This driver therefore
 * does NOT re-initialise the panel: prepare()/enable() are no-ops so the
 * running link is preserved, and the exynos9 DECON simply takes over scanning
 * its own framebuffer into the already-configured DSIM -> panel path.
 *
 * All this driver contributes is the DRM plumbing the DSI host needs: the DSI
 * device parameters (lane count, pixel format, command/video mode) and the
 * fixed native mode. Only the active resolution matters to the DECON; the
 * blanking is generated by the DSIM, which keeps the bootloader's values.
 */

#include <linux/backlight.h>
#include <linux/module.h>
#include <linux/of.h>

#include <drm/display/drm_dsc.h>
#include <drm/display/drm_dsc_helper.h>
#include <drm/drm_connector.h>
#include <drm/drm_crtc.h>
#include <drm/drm_mipi_dsi.h>
#include <drm/drm_modes.h>
#include <drm/drm_panel.h>

struct komodo_panel {
	struct drm_panel panel;
	struct mipi_dsi_device *dsi;
	/*
	 * Cached in get_modes() so enable() can read the active mode's refresh
	 * rate (connector->state->crtc->state), the idiomatic way a drm_panel
	 * learns its mode - see panel-novatek-nt35950.c. drm_panel itself has no
	 * mode_set callback.
	 */
	struct drm_connector *connector;
};

/*
 * komodo (google,gs-km4) WQHD DSC configuration, copied verbatim from the
 * vendor panel driver's wqhd_pps_config. This is the compression the DECON
 * emits; the panel's own DSC decoder must be programmed to match it, which is
 * what enable() sends (the vendor km4_enable(): DCS 0x9D 0x01 + this PPS).
 */
static const struct drm_dsc_config komodo_dsc_cfg = {
	.line_buf_depth = 9,
	.bits_per_component = 8,
	.convert_rgb = true,
	.slice_width = 672,
	.slice_height = 34,
	.slice_count = 2,
	.simple_422 = false,
	.pic_width = 1344,
	.pic_height = 2992,
	.rc_tgt_offset_high = 3,
	.rc_tgt_offset_low = 3,
	.bits_per_pixel = 128,
	.rc_edge_factor = 6,
	.rc_quant_incr_limit1 = 11,
	.rc_quant_incr_limit0 = 11,
	.initial_xmit_delay = 512,
	.initial_dec_delay = 592,
	.block_pred_enable = true,
	.first_line_bpg_offset = 12,
	.initial_offset = 6144,
	.rc_buf_thresh = {
		14, 28, 42, 56, 70, 84, 98, 105,
		112, 119, 121, 123, 125, 126
	},
	.rc_range_params = {
		{ 0, 4, 2 }, { 0, 4, 0 }, { 1, 5, 0 }, { 1, 6, 62 },
		{ 3, 7, 60 }, { 3, 7, 58 }, { 3, 7, 56 }, { 3, 8, 56 },
		{ 3, 9, 56 }, { 3, 10, 54 }, { 5, 11, 54 }, { 5, 12, 52 },
		{ 5, 13, 52 }, { 7, 13, 52 }, { 13, 15, 52 }
	},
	.rc_model_size = 8192,
	.flatness_min_qp = 3,
	.flatness_max_qp = 12,
	.initial_scale_value = 32,
	.scale_decrement_interval = 9,
	.scale_increment_interval = 932,
	.nfl_bpg_offset = 745,
	.slice_bpg_offset = 616,
	.final_offset = 4336,
	.vbr_enable = false,
	.slice_chunk_size = 672,
	.dsc_version_minor = 2,
	.dsc_version_major = 1,
};

static inline struct komodo_panel *to_komodo_panel(struct drm_panel *panel)
{
	return container_of(panel, struct komodo_panel, panel);
}

/*
 * Native 60 Hz timing for the komodo (google,gs-km4) panel, taken verbatim
 * from the vendor panel driver:
 *   DRM_MODE_TIMING(60, 1344, 80, 24, 42, 2992, 12, 4, 22)
 * i.e. hfp=80 hsa=24 hbp=42 (htotal 1490), vfp=12 vsa=4 vbp=22 (vtotal 3030).
 * Only hdisplay/vdisplay reach the DECON; the DSIM retains the bootloader
 * blanking. The link is dual-DSC compressed (8.0bpp, 2x 672-wide slices).
 */
#define KOMODO_MODE(hz, flags)						\
	{								\
		.clock = 1490 * 3030 * (hz) / 1000,			\
		.hdisplay = 1344,					\
		.hsync_start = 1344 + 80,				\
		.hsync_end = 1344 + 80 + 24,				\
		.htotal = 1344 + 80 + 24 + 42,				\
		.vdisplay = 2992,					\
		.vsync_start = 2992 + 12,				\
		.vsync_end = 2992 + 12 + 4,				\
		.vtotal = 2992 + 12 + 4 + 22,				\
		.width_mm = 70,						\
		.height_mm = 156,					\
		.type = DRM_MODE_TYPE_DRIVER | (flags),			\
	}

/*
 * The panel runs the same DSC link and blanking at both rates; only the panel's
 * operating frequency (DCS 0x60) and the DSIM TE timeout differ. 120 Hz is the
 * preferred/default; 60 Hz is selectable via a modeset.
 */
static const struct drm_display_mode komodo_modes[] = {
	KOMODO_MODE(120, DRM_MODE_TYPE_PREFERRED),
	KOMODO_MODE(60, 0),
};

/* Panel is already powered and streaming from the bootloader: keep it as-is. */
static int komodo_panel_noop(struct drm_panel *panel)
{
	return 0;
}

/*
 * The bootloader powered the panel and ran its full init, but the DECON now
 * drives a freshly-programmed dual-DSC command stream. (Re)program the panel's
 * DSC decoder to match, mirroring the vendor km4_enable() DSC path, and
 * (re)assert TE + display-on so the panel accepts the DECON-driven GRAM writes.
 */
/* Send a DCS command with inline bytes (cmd + params) to the panel. */
#define km4_feat(dsi, seq...)                                                  \
	mipi_dsi_dcs_write_buffer((dsi), (const u8[]){ seq },                  \
				  sizeof((const u8[]){ seq }))

static int komodo_cur_vrefresh(struct komodo_panel *ctx);

static int komodo_panel_enable(struct drm_panel *panel)
{
	struct komodo_panel *ctx = to_komodo_panel(panel);
	struct mipi_dsi_device *dsi = ctx->dsi;
	struct drm_dsc_picture_parameter_set pps;
	static const u8 dsc_en[] = { 0x9D, 0x01 };
	int ret;

	/*
	 * Replicate the vendor km4_enable() handover path 1:1 (needs_reset =
	 * false: the bootloader already lit the panel, so the reset / sleep-out /
	 * init_cmdset are skipped). The panel is re-pointed at the driver's
	 * freshly-programmed dual-DSC command stream and put into continuous
	 * 60Hz HS operation (early-exit OFF, manual FI OFF) so it accepts the
	 * DECON-driven write_memory instead of self-refreshing its splash GRAM.
	 * Since the bootloader already sent Display On, we do NOT re-send it
	 * (matching the vendor, whose 0x29 is gated on needs_reset || BLANK).
	 */

	/* DSC: enable + PPS (vendor: 0x9D 0x01 + gs_dcs_write_dsc_config()) */
	mipi_dsi_dcs_write_buffer(dsi, dsc_en, sizeof(dsc_en));
	drm_dsc_pps_payload_pack(&pps, &komodo_dsc_cfg);
	ret = mipi_dsi_picture_parameter_set(dsi, &pps);
	if (ret < 0)
		dev_err(&dsi->dev, "failed to send DSC PPS: %d\n", ret);

	/* Resolution / bit-depth config block (WQHD, 8-bit) */
	km4_feat(dsi, 0xF0, 0x5A, 0x5A);				/* unlock */
	km4_feat(dsi, 0xC3, 0x0C);					/* WQHD */
	km4_feat(dsi, 0xB0, 0x00, 0x01, 0xF2);
	km4_feat(dsi, 0xF2, 0x01);					/* 8-bit */
	km4_feat(dsi, 0xF0, 0xA5, 0xA5);				/* lock */

	/*
	 * Full vendor km4_set_panel_feat() block for a fresh 60Hz HS enable
	 * (mrr-v1, no idle/HBM/VRR, IRC flat default). Sent as flat DCS writes
	 * to the running (bootloader-lit) panel.
	 */
	km4_feat(dsi, 0xF0, 0x5A, 0x5A);				/* unlock */
	/* TE (changeable) */
	km4_feat(dsi, 0xB9, 0x04);
	km4_feat(dsi, 0xB0, 0x00, 0x04, 0xB9);
	km4_feat(dsi, 0xB9, 0x0B, 0x9A, 0x00, 0x1F);
	/* HBM / IRC (flat default) */
	km4_feat(dsi, 0xB0, 0x02, 0x00, 0x92);
	km4_feat(dsi, 0x92, 0x00, 0x00, 0xFF, 0xD0);
	/* SP / burn-in settings */
	km4_feat(dsi, 0xB0, 0x02, 0xF3, 0x68);
	km4_feat(dsi, 0x68, 0x12, 0x16, 0x0B, 0x22, 0x23, 0x19);
	/* operating mode: HS */
	km4_feat(dsi, 0xF2, 0x01);
	km4_feat(dsi, 0x60, 0x00);
	/* early-exit off */
	km4_feat(dsi, 0xB0, 0x00, 0x01, 0xBD);
	km4_feat(dsi, 0xBD, 0x81);
	km4_feat(dsi, 0xB0, 0x00, 0x10, 0xBD);
	km4_feat(dsi, 0xBD, 0x00);
	km4_feat(dsi, 0xB0, 0x00, 0x82, 0xBD);
	km4_feat(dsi, 0xBD, 0x00, 0x00, 0x00, 0x00);
	/* manual FI off */
	km4_feat(dsi, 0xB0, 0x00, 0x10, 0xBD);
	km4_feat(dsi, 0xBD, 0x00);
	km4_feat(dsi, 0xB0, 0x00, 0x82, 0xBD);
	km4_feat(dsi, 0xBD, 0x00, 0x00);
	km4_feat(dsi, 0xB0, 0x00, 0x80, 0xBD);
	km4_feat(dsi, 0xBD, 0x16);
	/* TSP sync */
	km4_feat(dsi, 0xB0, 0x00, 0x3C, 0xB9);
	km4_feat(dsi, 0xB9, 0x19, 0x09);
	km4_feat(dsi, 0xB0, 0x00, 0x05, 0xF2);
	km4_feat(dsi, 0xF2, 0xD0);
	km4_feat(dsi, 0xB0, 0x00, 0x41, 0xB9);
	km4_feat(dsi, 0xB9, 0x02);
	/* frequency: manual HS - 0x60 selects the rate (0x00 = 120Hz, 0x01 = 60Hz) */
	km4_feat(dsi, 0xBD, 0x21);
	km4_feat(dsi, 0x60, komodo_cur_vrefresh(ctx) == 120 ? 0x00 : 0x01);
	km4_feat(dsi, 0xF7, 0x0F);					/* freq update */
	km4_feat(dsi, 0xF0, 0xA5, 0xA5);				/* lock */

	/* WRCTRLD: enable brightness control (vendor km4_write_display_mode) */
	km4_feat(dsi, 0x53, 0x20);

	return 0;
}

static int komodo_panel_get_modes(struct drm_panel *panel,
				  struct drm_connector *connector)
{
	struct komodo_panel *ctx = to_komodo_panel(panel);
	unsigned int i;

	/* cache for cur_vrefresh() in enable() */
	ctx->connector = connector;

	for (i = 0; i < ARRAY_SIZE(komodo_modes); i++) {
		struct drm_display_mode *mode;

		mode = drm_mode_duplicate(connector->dev, &komodo_modes[i]);
		if (!mode)
			return i ? i : -ENOMEM;

		drm_mode_set_name(mode);
		drm_mode_probed_add(connector, mode);
	}

	connector->display_info.width_mm = komodo_modes[0].width_mm;
	connector->display_info.height_mm = komodo_modes[0].height_mm;

	return ARRAY_SIZE(komodo_modes);
}

/*
 * Read the active mode's refresh rate. drm_panel has no mode_set, so reach the
 * committed mode through the cached connector's atomic state (valid during the
 * enable phase of a modeset). Defaults to 60 Hz if the state is not available.
 */
static int komodo_cur_vrefresh(struct komodo_panel *ctx)
{
	struct drm_connector *conn = ctx->connector;

	if (conn && conn->state && conn->state->crtc &&
	    conn->state->crtc->state)
		return drm_mode_vrefresh(&conn->state->crtc->state->adjusted_mode);

	return 60;
}

static const struct drm_panel_funcs komodo_panel_funcs = {
	.prepare = komodo_panel_noop,
	.unprepare = komodo_panel_noop,
	.enable = komodo_panel_enable,
	.disable = komodo_panel_noop,
	.get_modes = komodo_panel_get_modes,
};

/*
 * Brightness: the panel level is a 12-bit DBV programmed over DSI (DCS 0x51,
 * MSB first - exactly mipi_dsi_dcs_set_display_brightness_large()). The enable
 * sequence already arms the brightness path (WRCTRLD BCTRL, 0x53 0x20).
 * Registering a backlight_device exposes /sys/class/backlight control, and
 * drm_panel enables/disables it around the panel so the DCS write only happens
 * while the link is up. The normal range tops out around DBV 3271; higher
 * values are the panel's HBM band, which needs its own enable sequence to
 * engage fully (not wired up yet).
 */
#define KOMODO_BRIGHTNESS_MAX	4095
#define KOMODO_BRIGHTNESS_DEFAULT 1300

static int komodo_bl_update_status(struct backlight_device *bl)
{
	struct komodo_panel *ctx = bl_get_data(bl);
	u16 brightness = backlight_get_brightness(bl);

	return mipi_dsi_dcs_set_display_brightness_large(ctx->dsi, brightness);
}

static const struct backlight_ops komodo_bl_ops = {
	.update_status = komodo_bl_update_status,
};

static int komodo_panel_backlight_init(struct komodo_panel *ctx)
{
	struct device *dev = &ctx->dsi->dev;
	const struct backlight_properties props = {
		.type = BACKLIGHT_RAW,
		.brightness = KOMODO_BRIGHTNESS_DEFAULT,
		.max_brightness = KOMODO_BRIGHTNESS_MAX,
	};
	struct backlight_device *bl;

	bl = devm_backlight_device_register(dev, dev_name(dev), dev, ctx,
					    &komodo_bl_ops, &props);
	if (IS_ERR(bl))
		return PTR_ERR(bl);

	ctx->panel.backlight = bl;
	return 0;
}

static int komodo_panel_probe(struct mipi_dsi_device *dsi)
{
	struct device *dev = &dsi->dev;
	struct komodo_panel *ctx;
	int ret;

	ctx = devm_drm_panel_alloc(dev, struct komodo_panel, panel,
				   &komodo_panel_funcs,
				   DRM_MODE_CONNECTOR_DSI);
	if (IS_ERR(ctx))
		return PTR_ERR(ctx);

	ctx->dsi = dsi;
	mipi_dsi_set_drvdata(dsi, ctx);

	dsi->lanes = 4;
	dsi->format = MIPI_DSI_FMT_RGB888;
	/*
	 * The komodo panel runs in MIPI command mode (LTPO OLED); the DECON is
	 * hardware-triggered from the panel TE. If a given unit's bootloader
	 * left the link in video mode instead, add MIPI_DSI_MODE_VIDEO here.
	 */
	dsi->mode_flags = MIPI_DSI_CLOCK_NON_CONTINUOUS;

	ctx->panel.prepare_prev_first = true;

	ret = komodo_panel_backlight_init(ctx);
	if (ret)
		return dev_err_probe(dev, ret, "failed to register backlight\n");

	drm_panel_add(&ctx->panel);

	ret = mipi_dsi_attach(dsi);
	if (ret < 0) {
		drm_panel_remove(&ctx->panel);
		return dev_err_probe(dev, ret, "failed to attach to DSI host\n");
	}

	return 0;
}

static void komodo_panel_remove(struct mipi_dsi_device *dsi)
{
	struct komodo_panel *ctx = mipi_dsi_get_drvdata(dsi);

	mipi_dsi_detach(dsi);
	drm_panel_remove(&ctx->panel);
}

static const struct of_device_id komodo_panel_of_match[] = {
	{ .compatible = "google,komodo-panel" },
	{ }
};
MODULE_DEVICE_TABLE(of, komodo_panel_of_match);

static struct mipi_dsi_driver komodo_panel_driver = {
	.probe = komodo_panel_probe,
	.remove = komodo_panel_remove,
	.driver = {
		.name = "panel-google-komodo",
		.of_match_table = komodo_panel_of_match,
	},
};
module_mipi_dsi_driver(komodo_panel_driver);

MODULE_DESCRIPTION("Google komodo (Pixel 9 Pro XL) boot-handoff panel driver");
MODULE_LICENSE("GPL");
